{{- with index .Values "cluster-configs" "secrets" "db" }}
{{- if index . "password" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  username: {{ .username | b64enc | quote }}
  password: {{ .password | b64enc | quote }}
  flyway-username: {{ .flywayUsername | b64enc | quote }}
  flyway-password: {{ .flywayPassword | b64enc | quote }}
{{- end }}
{{- end }}
