
{{- with index .Values "cluster-configs" "secrets" "egov-location" "gmaps" }}
{{- if index . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  gmapskey: {{ .gmaps | b64enc | quote }}
{{- end }}
{{- end }}