{{- with index .Values "cluster-configs" "secrets" "git-sync" }}
{{- if index . "ssh" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  ssh: {{ index . "ssh" | b64enc | quote }}
  known_hosts: {{ index . "known-hosts" | b64enc | quote }}
{{- end }}
{{- end }}
