cluster-configs:
  db:
    namespace: egov
    name: db-service
    port: 5432
    targetPort: 5432

  root-ingress:
    name: root-ingress
    namespace: egov
    cert-issuer: "letsencrypt-staging"
    appRoot: citizen
    serviceName: citizen
    servicePort: 80
 
  nginx-errors:
    name: nginx-errors
    namespace: egov
    serviceName: nginx-errors
    servicePort: 80

  configmaps:
    egov-config:
      namespace: egov
      name: egov-config
      server-tomcat-max-connections: "500"
      server-tomcat-max-threads: "10"
      spring-datasource-tomcat-initialSize: "1"
      spring-datasource-tomcat-max-active: "2"
      spring-jpa-show-sql: "true"  

    egov-service-host:    
      namespace: egov
      name: egov-service-host  

  secrets:
    db: 
      namespace: egov
      name: db

    egov-notification-sms:
      namespace: egov
      name: egov-notification-sms

    egov-filestore: 
      namespace: egov
      name: egov-filestore     
      
    egov-location: 
      namespace: egov
      name: egov-location

    egov-pg-service: 
      namespace: egov
      name: egov-pg-service                 

    pgadmin: 
      namespace: playground
      name: pgadmin       

    egov-enc-service: 
      namespace: egov
      name: egov-enc-service       

    egov-notification-mail: 
      namespace: egov
      name: egov-notification-mail

    git-sync: 
      namespace: egov
      name: git-creds   

    kibana: 
      namespace: egov
      name: kibana-creds                       

    kibana-infra: 
      namespace: egov
      name: kibana-infra-creds     

    pgadmin: 
      namespace: playground
      name: pgadmin

    egov-si-microservice:
      namespace: egov
      name: egov-si-microservice

    egov-edcr-notification:
      namespace: egov
      name: egov-edcr-notification 

    egov-edcr-bank-gateway:
      namespace: egov
      name: egov-edcr-bank-gateway

    chatbot:
      namespace: egov
      name: chatbot

    egov-user-chatbot:
      namespace: egov
      name: egov-user-chatbot

    oauth2-proxy:
      namespace: egov
      name: oauth2-proxy      



