{{- with index .Values "cluster-configs" "configmaps" "egov-service-host" }}
{{- if index . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
data:
{{- range $key, $value := .data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}