kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wt-support-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wt-support-clusterrolebinding
subjects:
- kind: User
  name: wt-support-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: wt-support-clusterrole
  apiGroup: rbac.authorization.k8s.io  