# creation rules are evaluated sequentially, the first match wins
creation_rules:
        # upon creation of a file that matches the pattern *dev.yaml,
        # KMS set A is used
        # eGOV Internal ------------------------------------------------------------------------------------------------------------- #
        - path_regex: environments/dev\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:123456789:key/abcdefg-12345
          gcp_kms: 'projects/digit-1234/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'   


        # ePASS ------------------------------------------------------------------------------------------------------------- #
        - path_regex: environments/egov\-demo\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:123456789:key/abcdefg-12345
          gcp_kms: 'projects/digit-1234/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'    

